### PR TITLE
Has capability test

### PR DESCRIPTION
**Pull request by nichoth**
This PR adds some tests for the `hasCapability` method. These were things that I was curious about when I was looking at how to validate permissions via UCAN. There is still one question I had, about the `originator` field. I made a test that currently fails -- https://github.com/nichoth/ts-ucan/blob/f2fde61b72adcd0a434e5ce1ba91cfe1d834fba1/tests/attenuation.test.ts#L296 -- the question is how is `originator` used? It doesn't seem to affect the return value of `hasCapability`. I'm not sure if this is not implemented yet or if my test is wrong in some way.

Thanks. Hopefully this is helpful and not creating needless work 😬

### CODE REVIEW

**Comment by matheus23** [comment]
Thanks, that's an *amazing* contribution.

> the question is how is originator used? It doesn't seem to affect the return value of hasCapability. I'm not sure if this is not implemented yet or if my test is wrong in some way.

Yes, this is a bug. Whoops! `hasCapability` should check the `originator` to make sure it matches what's passed in and also check that the time bounds work out. All of that *instead* of running `delegateCapabilityInfo`... My bad.

Your contribution is amazing. You've created a failing test case. We'll use that to implement a fix for this.

**Comment by icidasset** [comment]
@nichoth Any chance you can rebase this on `main`? It should only be two merge conflicts, because the path of `./emailCapabilities` has changed to `./capabilities/email`, and I changed `emailCaps = Array.from(` to be multiline.

Would love to get this in so we can fix `hasCapability` 🙏

**Review by icidasset — APPROVED** [review]
Thanks! 🙌 I'll merge this next Monday and will make sure all the tests pass.

**Comment by nichoth** [comment]
I just fixed the type checking with the updates, however there is one type I wasn't sure about -- https://github.com/nichoth/ts-ucan/blob/hasCapability-test/tests/attenuation.test.ts#L234

It is telling me
```
Property 'email' does not exist on type 'Capability'.ts(2339)
```

image

**Comment by matheus23** [comment]
@nichoth this PR is almost good to go. I proposed some changes to this PR in another PR (see the mention above this comment :point_up_2: ).

Once we've merged *that* PR, we can merge *this* PR :tada:

**Review by matheus23 — APPROVED** [review]
Okay. I'd love to merge this.

With my changes this also fixes #60 

I'd love to see another quick look at this @icidasset :pray:

**Comment by icidasset** [comment]
Looks good! 👏

**Pull request merged**
