### PR TITLE
Added public key compression for NIST P-256 keys

### PR DESCRIPTION
**Pull request by dholms**
## Problem
The did:key spec says that NIST P-256 keys should be represented as the base58 encoding of the 33-byte compressed public key. Currently, we were base58 encoding the spki public key representation.

## Solution
Export keys as the raw 65 byte public key & compress keys before creating DID. When moving from DID to public key, we have to decompress the keys.

_Note: I only implemented this for NIST P-256, not P-384 or P-521. It's the same algorithm but different curve params_

Closes https://github.com/ucan-wg/ts-ucan/issues/80

### CODE REVIEW

**Comment by dholms** [comment]
> How much effort would implementing this for P-384 and P-521 be? Is it just a matter of plugging in the right curve parameters in exactly the same algorithm?
Yeah same algo, just different params. I don't know of anyone that's using those curves, so I'm leaning towards just cutting them out for now & we can easily add them back in if someone needs them (we can leave the magic bytes around for now so we don't have to do any recalculating)

> I know you probably just haven't gotten around to it yet, but I'd love to test the [did-key-method test vectors](https://github.com/w3c-ccg/did-method-key/blob/main/test-vectors/nist-curves.json) against this implementation (they include the corresponding private keys as JWKs).

Yes that sounds great to me! Maybe we can get those in with the refactor

**Comment by matheus23** [comment]
> I think this is ready to go :man_dancing:

Can we get in just a couple of those test-vector tests, please? That's the thing that went wrong the last time we merged something like this, so I'd love to do it right this time around :sweat_smile: 

Literally just copying over the test vector secret keys from the DID spec I linked to, importing them into WebCrypto as JWKs, turning those keys into `EcdsaKeypair` and seeing if `.did()` matches up with what's in the test vectors :pray:

**Comment by dholms** [comment]
Yeah can do 👍

**Comment by dholms** [comment]
Alrighty sweet got those added in 👍 lmk how that looks

**Review by matheus23 — APPROVED** [review]
Awesome :) feel free to push the button :D

**Pull request merged**
